# inventory.ini — generated by Tango Bootstrap Cluster
# Replace the placeholder values with your actual server IPs.
# This file is for manual use; the Tango UI generates it automatically.

[control_plane]
k8s-master ansible_host=<MASTER_PUBLIC_IP> ansible_user=root node_ip=<MASTER_PRIVATE_OR_PUBLIC_IP> ansible_port=22

[workers]
k8s-worker1 ansible_host=<WORKER1_PUBLIC_IP> ansible_user=root node_ip=<WORKER1_PRIVATE_OR_PUBLIC_IP> ansible_port=22

[k8s:children]
control_plane
workers

[k8s:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
