/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthAccountRouteImport } from './routes/_auth/account'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthSwarmIndexRouteImport } from './routes/_auth/swarm/index'
import { Route as AuthSourcesIndexRouteImport } from './routes/_auth/sources/index'
import { Route as AuthServersIndexRouteImport } from './routes/_auth/servers/index'
import { Route as AuthRolesIndexRouteImport } from './routes/_auth/roles/index'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth/projects/index'
import { Route as AuthDomainsIndexRouteImport } from './routes/_auth/domains/index'
import { Route as AuthDatabasesIndexRouteImport } from './routes/_auth/databases/index'
import { Route as AuthContainersIndexRouteImport } from './routes/_auth/containers/index'
import { Route as AuthClustersIndexRouteImport } from './routes/_auth/clusters/index'
import { Route as AuthCloudflareIndexRouteImport } from './routes/_auth/cloudflare/index'
import { Route as AuthChannelsIndexRouteImport } from './routes/_auth/channels/index'
import { Route as AuthBuildsIndexRouteImport } from './routes/_auth/builds/index'
import { Route as AuthUsersCreateRouteImport } from './routes/_auth/users/create'
import { Route as AuthResourcesResourceIdRouteImport } from './routes/_auth/resources/$resourceId'
import { Route as AuthProjectsProjectIdRouteImport } from './routes/_auth/projects/$projectId'
import { Route as AuthClustersNewRouteImport } from './routes/_auth/clusters/new'
import { Route as AuthClustersClusterIdRouteImport } from './routes/_auth/clusters/$clusterId'
import { Route as AuthChannelsCreateRouteImport } from './routes/_auth/channels/create'
import { Route as AuthUsersUserIdEditRouteImport } from './routes/_auth/users/$userId/edit'
import { Route as AuthChannelsChannelIdEditRouteImport } from './routes/_auth/channels/$channelId/edit'
import { Route as AuthEnvironmentsEnvIdResourcesNewRouteImport } from './routes/_auth/environments/$envId/resources/new'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSwarmIndexRoute = AuthSwarmIndexRouteImport.update({
  id: '/swarm/',
  path: '/swarm/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSourcesIndexRoute = AuthSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthServersIndexRoute = AuthServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesIndexRoute = AuthRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDomainsIndexRoute = AuthDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDatabasesIndexRoute = AuthDatabasesIndexRouteImport.update({
  id: '/databases/',
  path: '/databases/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContainersIndexRoute = AuthContainersIndexRouteImport.update({
  id: '/containers/',
  path: '/containers/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClustersIndexRoute = AuthClustersIndexRouteImport.update({
  id: '/clusters/',
  path: '/clusters/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCloudflareIndexRoute = AuthCloudflareIndexRouteImport.update({
  id: '/cloudflare/',
  path: '/cloudflare/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChannelsIndexRoute = AuthChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBuildsIndexRoute = AuthBuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersCreateRoute = AuthUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResourcesResourceIdRoute = AuthResourcesResourceIdRouteImport.update({
  id: '/resources/$resourceId',
  path: '/resources/$resourceId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsProjectIdRoute = AuthProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClustersNewRoute = AuthClustersNewRouteImport.update({
  id: '/clusters/new',
  path: '/clusters/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClustersClusterIdRoute = AuthClustersClusterIdRouteImport.update({
  id: '/clusters/$clusterId',
  path: '/clusters/$clusterId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChannelsCreateRoute = AuthChannelsCreateRouteImport.update({
  id: '/channels/create',
  path: '/channels/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersUserIdEditRoute = AuthUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChannelsChannelIdEditRoute =
  AuthChannelsChannelIdEditRouteImport.update({
    id: '/channels/$channelId/edit',
    path: '/channels/$channelId/edit',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthEnvironmentsEnvIdResourcesNewRoute =
  AuthEnvironmentsEnvIdResourcesNewRouteImport.update({
    id: '/environments/$envId/resources/new',
    path: '/environments/$envId/resources/new',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AuthAccountRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/channels/create': typeof AuthChannelsCreateRoute
  '/clusters/$clusterId': typeof AuthClustersClusterIdRoute
  '/clusters/new': typeof AuthClustersNewRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/resources/$resourceId': typeof AuthResourcesResourceIdRoute
  '/users/create': typeof AuthUsersCreateRoute
  '/builds/': typeof AuthBuildsIndexRoute
  '/channels/': typeof AuthChannelsIndexRoute
  '/cloudflare/': typeof AuthCloudflareIndexRoute
  '/clusters/': typeof AuthClustersIndexRoute
  '/containers/': typeof AuthContainersIndexRoute
  '/databases/': typeof AuthDatabasesIndexRoute
  '/domains/': typeof AuthDomainsIndexRoute
  '/projects/': typeof AuthProjectsIndexRoute
  '/roles/': typeof AuthRolesIndexRoute
  '/servers/': typeof AuthServersIndexRoute
  '/sources/': typeof AuthSourcesIndexRoute
  '/swarm/': typeof AuthSwarmIndexRoute
  '/users/': typeof AuthUsersIndexRoute
  '/channels/$channelId/edit': typeof AuthChannelsChannelIdEditRoute
  '/users/$userId/edit': typeof AuthUsersUserIdEditRoute
  '/environments/$envId/resources/new': typeof AuthEnvironmentsEnvIdResourcesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AuthAccountRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/channels/create': typeof AuthChannelsCreateRoute
  '/clusters/$clusterId': typeof AuthClustersClusterIdRoute
  '/clusters/new': typeof AuthClustersNewRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/resources/$resourceId': typeof AuthResourcesResourceIdRoute
  '/users/create': typeof AuthUsersCreateRoute
  '/builds': typeof AuthBuildsIndexRoute
  '/channels': typeof AuthChannelsIndexRoute
  '/cloudflare': typeof AuthCloudflareIndexRoute
  '/clusters': typeof AuthClustersIndexRoute
  '/containers': typeof AuthContainersIndexRoute
  '/databases': typeof AuthDatabasesIndexRoute
  '/domains': typeof AuthDomainsIndexRoute
  '/projects': typeof AuthProjectsIndexRoute
  '/roles': typeof AuthRolesIndexRoute
  '/servers': typeof AuthServersIndexRoute
  '/sources': typeof AuthSourcesIndexRoute
  '/swarm': typeof AuthSwarmIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/channels/$channelId/edit': typeof AuthChannelsChannelIdEditRoute
  '/users/$userId/edit': typeof AuthUsersUserIdEditRoute
  '/environments/$envId/resources/new': typeof AuthEnvironmentsEnvIdResourcesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_auth/account': typeof AuthAccountRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_auth/channels/create': typeof AuthChannelsCreateRoute
  '/_auth/clusters/$clusterId': typeof AuthClustersClusterIdRoute
  '/_auth/clusters/new': typeof AuthClustersNewRoute
  '/_auth/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/_auth/resources/$resourceId': typeof AuthResourcesResourceIdRoute
  '/_auth/users/create': typeof AuthUsersCreateRoute
  '/_auth/builds/': typeof AuthBuildsIndexRoute
  '/_auth/channels/': typeof AuthChannelsIndexRoute
  '/_auth/cloudflare/': typeof AuthCloudflareIndexRoute
  '/_auth/clusters/': typeof AuthClustersIndexRoute
  '/_auth/containers/': typeof AuthContainersIndexRoute
  '/_auth/databases/': typeof AuthDatabasesIndexRoute
  '/_auth/domains/': typeof AuthDomainsIndexRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
  '/_auth/roles/': typeof AuthRolesIndexRoute
  '/_auth/servers/': typeof AuthServersIndexRoute
  '/_auth/sources/': typeof AuthSourcesIndexRoute
  '/_auth/swarm/': typeof AuthSwarmIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/channels/$channelId/edit': typeof AuthChannelsChannelIdEditRoute
  '/_auth/users/$userId/edit': typeof AuthUsersUserIdEditRoute
  '/_auth/environments/$envId/resources/new': typeof AuthEnvironmentsEnvIdResourcesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/register'
    | '/channels/create'
    | '/clusters/$clusterId'
    | '/clusters/new'
    | '/projects/$projectId'
    | '/resources/$resourceId'
    | '/users/create'
    | '/builds/'
    | '/channels/'
    | '/cloudflare/'
    | '/clusters/'
    | '/containers/'
    | '/databases/'
    | '/domains/'
    | '/projects/'
    | '/roles/'
    | '/servers/'
    | '/sources/'
    | '/swarm/'
    | '/users/'
    | '/channels/$channelId/edit'
    | '/users/$userId/edit'
    | '/environments/$envId/resources/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/register'
    | '/channels/create'
    | '/clusters/$clusterId'
    | '/clusters/new'
    | '/projects/$projectId'
    | '/resources/$resourceId'
    | '/users/create'
    | '/builds'
    | '/channels'
    | '/cloudflare'
    | '/clusters'
    | '/containers'
    | '/databases'
    | '/domains'
    | '/projects'
    | '/roles'
    | '/servers'
    | '/sources'
    | '/swarm'
    | '/users'
    | '/channels/$channelId/edit'
    | '/users/$userId/edit'
    | '/environments/$envId/resources/new'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/account'
    | '/_auth/dashboard'
    | '/_auth/settings'
    | '/_guest/login'
    | '/_guest/register'
    | '/_auth/channels/create'
    | '/_auth/clusters/$clusterId'
    | '/_auth/clusters/new'
    | '/_auth/projects/$projectId'
    | '/_auth/resources/$resourceId'
    | '/_auth/users/create'
    | '/_auth/builds/'
    | '/_auth/channels/'
    | '/_auth/cloudflare/'
    | '/_auth/clusters/'
    | '/_auth/containers/'
    | '/_auth/databases/'
    | '/_auth/domains/'
    | '/_auth/projects/'
    | '/_auth/roles/'
    | '/_auth/servers/'
    | '/_auth/sources/'
    | '/_auth/swarm/'
    | '/_auth/users/'
    | '/_auth/channels/$channelId/edit'
    | '/_auth/users/$userId/edit'
    | '/_auth/environments/$envId/resources/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account': {
      id: '/_auth/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/swarm/': {
      id: '/_auth/swarm/'
      path: '/swarm'
      fullPath: '/swarm/'
      preLoaderRoute: typeof AuthSwarmIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sources/': {
      id: '/_auth/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof AuthSourcesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/servers/': {
      id: '/_auth/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthServersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles/': {
      id: '/_auth/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthRolesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/domains/': {
      id: '/_auth/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof AuthDomainsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/databases/': {
      id: '/_auth/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof AuthDatabasesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/containers/': {
      id: '/_auth/containers/'
      path: '/containers'
      fullPath: '/containers/'
      preLoaderRoute: typeof AuthContainersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clusters/': {
      id: '/_auth/clusters/'
      path: '/clusters'
      fullPath: '/clusters/'
      preLoaderRoute: typeof AuthClustersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cloudflare/': {
      id: '/_auth/cloudflare/'
      path: '/cloudflare'
      fullPath: '/cloudflare/'
      preLoaderRoute: typeof AuthCloudflareIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/channels/': {
      id: '/_auth/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof AuthChannelsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/builds/': {
      id: '/_auth/builds/'
      path: '/builds'
      fullPath: '/builds/'
      preLoaderRoute: typeof AuthBuildsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/create': {
      id: '/_auth/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthUsersCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/resources/$resourceId': {
      id: '/_auth/resources/$resourceId'
      path: '/resources/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof AuthResourcesResourceIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$projectId': {
      id: '/_auth/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthProjectsProjectIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clusters/new': {
      id: '/_auth/clusters/new'
      path: '/clusters/new'
      fullPath: '/clusters/new'
      preLoaderRoute: typeof AuthClustersNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clusters/$clusterId': {
      id: '/_auth/clusters/$clusterId'
      path: '/clusters/$clusterId'
      fullPath: '/clusters/$clusterId'
      preLoaderRoute: typeof AuthClustersClusterIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/channels/create': {
      id: '/_auth/channels/create'
      path: '/channels/create'
      fullPath: '/channels/create'
      preLoaderRoute: typeof AuthChannelsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/$userId/edit': {
      id: '/_auth/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthUsersUserIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/channels/$channelId/edit': {
      id: '/_auth/channels/$channelId/edit'
      path: '/channels/$channelId/edit'
      fullPath: '/channels/$channelId/edit'
      preLoaderRoute: typeof AuthChannelsChannelIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/environments/$envId/resources/new': {
      id: '/_auth/environments/$envId/resources/new'
      path: '/environments/$envId/resources/new'
      fullPath: '/environments/$envId/resources/new'
      preLoaderRoute: typeof AuthEnvironmentsEnvIdResourcesNewRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccountRoute: typeof AuthAccountRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthChannelsCreateRoute: typeof AuthChannelsCreateRoute
  AuthClustersClusterIdRoute: typeof AuthClustersClusterIdRoute
  AuthClustersNewRoute: typeof AuthClustersNewRoute
  AuthProjectsProjectIdRoute: typeof AuthProjectsProjectIdRoute
  AuthResourcesResourceIdRoute: typeof AuthResourcesResourceIdRoute
  AuthUsersCreateRoute: typeof AuthUsersCreateRoute
  AuthBuildsIndexRoute: typeof AuthBuildsIndexRoute
  AuthChannelsIndexRoute: typeof AuthChannelsIndexRoute
  AuthCloudflareIndexRoute: typeof AuthCloudflareIndexRoute
  AuthClustersIndexRoute: typeof AuthClustersIndexRoute
  AuthContainersIndexRoute: typeof AuthContainersIndexRoute
  AuthDatabasesIndexRoute: typeof AuthDatabasesIndexRoute
  AuthDomainsIndexRoute: typeof AuthDomainsIndexRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
  AuthRolesIndexRoute: typeof AuthRolesIndexRoute
  AuthServersIndexRoute: typeof AuthServersIndexRoute
  AuthSourcesIndexRoute: typeof AuthSourcesIndexRoute
  AuthSwarmIndexRoute: typeof AuthSwarmIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthChannelsChannelIdEditRoute: typeof AuthChannelsChannelIdEditRoute
  AuthUsersUserIdEditRoute: typeof AuthUsersUserIdEditRoute
  AuthEnvironmentsEnvIdResourcesNewRoute: typeof AuthEnvironmentsEnvIdResourcesNewRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountRoute: AuthAccountRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthChannelsCreateRoute: AuthChannelsCreateRoute,
  AuthClustersClusterIdRoute: AuthClustersClusterIdRoute,
  AuthClustersNewRoute: AuthClustersNewRoute,
  AuthProjectsProjectIdRoute: AuthProjectsProjectIdRoute,
  AuthResourcesResourceIdRoute: AuthResourcesResourceIdRoute,
  AuthUsersCreateRoute: AuthUsersCreateRoute,
  AuthBuildsIndexRoute: AuthBuildsIndexRoute,
  AuthChannelsIndexRoute: AuthChannelsIndexRoute,
  AuthCloudflareIndexRoute: AuthCloudflareIndexRoute,
  AuthClustersIndexRoute: AuthClustersIndexRoute,
  AuthContainersIndexRoute: AuthContainersIndexRoute,
  AuthDatabasesIndexRoute: AuthDatabasesIndexRoute,
  AuthDomainsIndexRoute: AuthDomainsIndexRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
  AuthRolesIndexRoute: AuthRolesIndexRoute,
  AuthServersIndexRoute: AuthServersIndexRoute,
  AuthSourcesIndexRoute: AuthSourcesIndexRoute,
  AuthSwarmIndexRoute: AuthSwarmIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthChannelsChannelIdEditRoute: AuthChannelsChannelIdEditRoute,
  AuthUsersUserIdEditRoute: AuthUsersUserIdEditRoute,
  AuthEnvironmentsEnvIdResourcesNewRoute:
    AuthEnvironmentsEnvIdResourcesNewRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
